version: "3.9"

services:
  api:
    build: .
    ports:
      - "8100:8000"
    env_file: .env
    volumes:
      - model_cache:/root/.cache/huggingface
    depends_on:
      - redis
      - mongo
      - seaweedfs
    mem_limit: 2g

  worker:
    build: .
    command: celery -A worker worker --concurrency=1 --prefetch-multiplier=1 --loglevel=info
    env_file: .env
    environment:
      - OMP_NUM_THREADS=2
    volumes:
      - model_cache:/root/.cache/huggingface
    depends_on:
      - redis
      - mongo
      - seaweedfs
    mem_limit: 4g

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    command: "server -s3 -s3.port=8333 -dir=/data"
    ports:
      - "8333:8333"
    volumes:
      - /mnt/mnt2/Simple/faster-whisper/service/.seaweedfs_data:/data
    mem_limit: 1g

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    mem_limit: 512m

volumes:
  seaweed_data:
  model_cache:
  redis_data:
  mongo_data:
